/**
 * Generator module - generates TypeScript from analysis
 */

import type { PluginAnalysis } from './types';

import { logger } from './logger';

/**
 * Generate TypeScript header
 */
function generateHeader(pluginVersion?: string): string {
  const ourVersion = '0.0.0'; // TODO: get from package.json
  return `/**
 * DO NOT EDIT - This file is generated by vue-types-gen
 * 
 * @poupe/eslint-plugin-vue-types: v${ourVersion}
 * eslint-plugin-vue: v${pluginVersion || 'unknown'}
 * 
 * Rule type definitions for eslint-plugin-vue
 * Compatible with ESLint 9.x type requirements
 */

/* eslint-disable */

`;
}

/**
 * Generate complete TypeScript file
 */
export async function generateTypescript(
  analysis: PluginAnalysis,
): Promise<string> {
  const sections: string[] = [];

  // Header
  sections.push(
    generateHeader(analysis.pluginVersion),
    'export default {} as unknown;',
    '',
  );

  // Log analysis info
  logger.info('Analysis complete:');
  logger.info(`  Total rules: ${analysis.totalRules}`);
  logger.info(`  Rules with options: ${analysis.rulesWithOptions}`);
  logger.info(`  Rules without options: ${analysis.rulesWithoutOptions}`);

  // Join all sections
  return sections.join('\n');
}
